--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.order_preestimate_shipping_list_order_item_inner_order_item_option_inner
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("order_preestimate_shipping_list_order_item_inner_order_item_option_inner", function()
  local openapiclient_order_preestimate_shipping_list_order_item_inner_order_item_option_inner = require "openapiclient.model.order_preestimate_shipping_list_order_item_inner_order_item_option_inner"

  -- unit tests for the property 'order_item_option_name'
  describe("property order_item_option_name test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'order_item_option_id'
  describe("property order_item_option_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'order_item_option_value'
  describe("property order_item_option_value test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'order_item_option_value_id'
  describe("property order_item_option_value_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'order_item_option_used_in_combinations'
  describe("property order_item_option_used_in_combinations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
