--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.param_definition_filtering_conditions_filter_rule_value
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("param_definition_filtering_conditions_filter_rule_value", function()
  local openapiclient_param_definition_filtering_conditions_filter_rule_value = require "openapiclient.model.param_definition_filtering_conditions_filter_rule_value"

end)
