--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.product_add_batch_payload_inner_sales_tax
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("product_add_batch_payload_inner_sales_tax", function()
  local openapiclient_product_add_batch_payload_inner_sales_tax = require "openapiclient.model.product_add_batch_payload_inner_sales_tax"

  -- unit tests for the property 'tax_percent'
  describe("property tax_percent test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'taxable'
  describe("property taxable test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
