--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.product_add_best_offer
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("product_add_best_offer", function()
  local openapiclient_product_add_best_offer = require "openapiclient.model.product_add_best_offer"

  -- unit tests for the property 'minimum_offer_price'
  describe("property minimum_offer_price test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'auto_accept_price'
  describe("property auto_accept_price test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
