--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model.product_add_certifications_inner_files_inner
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("product_add_certifications_inner_files_inner", function()
  local openapiclient_product_add_certifications_inner_files_inner = require "openapiclient.model.product_add_certifications_inner_files_inner"

  -- unit tests for the property 'url'
  describe("property url test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
