--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

--package openapiclient

local http_request = require "http.request"
local http_util = require "http.util"
local dkjson = require "dkjson"
local basexx = require "basexx"

-- model import
local openapiclient_response_analytics_customer_report_result = require "openapiclient.model.response_analytics_customer_report_result"
local openapiclient_response_analytics_product_report_result = require "openapiclient.model.response_analytics_product_report_result"
local openapiclient_response_analytics_report_result = require "openapiclient.model.response_analytics_report_result"

local analytics_api = {}
local analytics_api_mt = {
	__name = "analytics_api";
	__index = analytics_api;
}

local function new_analytics_api(authority, basePath, schemes)
	local schemes_map = {}
	for _,v in ipairs(schemes) do
		schemes_map[v] = v
	end
	local default_scheme = schemes_map.https or schemes_map.http
	local host, port = http_util.split_authority(authority, default_scheme)
	return setmetatable({
		host = host;
		port = port;
		basePath = basePath or "https://api.api2cart.local.com/v1.1";
		schemes = schemes_map;
		default_scheme = default_scheme;
		http_username = nil;
		http_password = nil;
		api_key = {};
		access_token = nil;
	}, analytics_api_mt)
end

function analytics_api:analytics_customer_report(date_from, date_to, count, currency_id, store_id, customer_type, email, sort_by, sort_direction, page_cursor, response_fields)
	local req = http_request.new_from_uri({
		scheme = self.default_scheme;
		host = self.host;
		port = self.port;
		path = string.format("%s/analytics.customer_report.json?date_from=%s&date_to=%s&count=%s&currency_id=%s&store_id=%s&customer_type=%s&email=%s&sort_by=%s&sort_direction=%s&page_cursor=%s&response_fields=%s",
			self.basePath, http_util.encodeURIComponent(date_from), http_util.encodeURIComponent(date_to), http_util.encodeURIComponent(count), http_util.encodeURIComponent(currency_id), http_util.encodeURIComponent(store_id), http_util.encodeURIComponent(customer_type), http_util.encodeURIComponent(email), http_util.encodeURIComponent(sort_by), http_util.encodeURIComponent(sort_direction), http_util.encodeURIComponent(page_cursor), http_util.encodeURIComponent(response_fields));
	})

	-- set HTTP verb
	req.headers:upsert(":method", "GET")
	-- TODO: create a function to select proper content-type
	--local var_accept = { "application/json" }
	req.headers:upsert("content-type", "application/json")

	-- api key in headers 'x-store-key'
	if self.api_key['x-store-key'] then
		req.headers:upsert("StoreKeyAuth", self.api_key['x-store-key'])
	end
	-- api key in headers 'x-api-key'
	if self.api_key['x-api-key'] then
		req.headers:upsert("ApiKeyAuth", self.api_key['x-api-key'])
	end

	-- make the HTTP call
	local headers, stream, errno = req:go()
	if not headers then
		return nil, stream, errno
	end
	local http_status = headers:get(":status")
	if http_status:sub(1,1) == "2" then
		local body, err, errno2 = stream:get_body_as_string()
		-- exception when getting the HTTP body
		if not body then
			return nil, err, errno2
		end
		stream:shutdown()
		local result, _, err3 = dkjson.decode(body)
		-- exception when decoding the HTTP body
		if result == nil then
			return nil, err3
		end
		return openapiclient_response_analytics_customer_report_result.cast(result), headers
	else
		local body, err, errno2 = stream:get_body_as_string()
		if not body then
			return nil, err, errno2
		end
		stream:shutdown()
		-- return the error message (http body)
		return nil, http_status, body
	end
end

function analytics_api:analytics_product_report(date_from, date_to, count, product_ids, currency_id, store_id, categories_ids, sort_by, sort_direction, page_cursor, response_fields)
	local req = http_request.new_from_uri({
		scheme = self.default_scheme;
		host = self.host;
		port = self.port;
		path = string.format("%s/analytics.product_report.json?date_from=%s&date_to=%s&count=%s&product_ids=%s&currency_id=%s&store_id=%s&categories_ids=%s&sort_by=%s&sort_direction=%s&page_cursor=%s&response_fields=%s",
			self.basePath, http_util.encodeURIComponent(date_from), http_util.encodeURIComponent(date_to), http_util.encodeURIComponent(count), http_util.encodeURIComponent(product_ids), http_util.encodeURIComponent(currency_id), http_util.encodeURIComponent(store_id), http_util.encodeURIComponent(categories_ids), http_util.encodeURIComponent(sort_by), http_util.encodeURIComponent(sort_direction), http_util.encodeURIComponent(page_cursor), http_util.encodeURIComponent(response_fields));
	})

	-- set HTTP verb
	req.headers:upsert(":method", "GET")
	-- TODO: create a function to select proper content-type
	--local var_accept = { "application/json" }
	req.headers:upsert("content-type", "application/json")

	-- api key in headers 'x-store-key'
	if self.api_key['x-store-key'] then
		req.headers:upsert("StoreKeyAuth", self.api_key['x-store-key'])
	end
	-- api key in headers 'x-api-key'
	if self.api_key['x-api-key'] then
		req.headers:upsert("ApiKeyAuth", self.api_key['x-api-key'])
	end

	-- make the HTTP call
	local headers, stream, errno = req:go()
	if not headers then
		return nil, stream, errno
	end
	local http_status = headers:get(":status")
	if http_status:sub(1,1) == "2" then
		local body, err, errno2 = stream:get_body_as_string()
		-- exception when getting the HTTP body
		if not body then
			return nil, err, errno2
		end
		stream:shutdown()
		local result, _, err3 = dkjson.decode(body)
		-- exception when decoding the HTTP body
		if result == nil then
			return nil, err3
		end
		return openapiclient_response_analytics_product_report_result.cast(result), headers
	else
		local body, err, errno2 = stream:get_body_as_string()
		if not body then
			return nil, err, errno2
		end
		stream:shutdown()
		-- return the error message (http body)
		return nil, http_status, body
	end
end

function analytics_api:analytics_report(date_from, date_to, interval, order_status, financial_status, currency_id, store_id, sort_by, sort_direction, response_fields)
	local req = http_request.new_from_uri({
		scheme = self.default_scheme;
		host = self.host;
		port = self.port;
		path = string.format("%s/analytics.report.json?date_from=%s&date_to=%s&interval=%s&order_status=%s&financial_status=%s&currency_id=%s&store_id=%s&sort_by=%s&sort_direction=%s&response_fields=%s",
			self.basePath, http_util.encodeURIComponent(date_from), http_util.encodeURIComponent(date_to), http_util.encodeURIComponent(interval), http_util.encodeURIComponent(order_status), http_util.encodeURIComponent(financial_status), http_util.encodeURIComponent(currency_id), http_util.encodeURIComponent(store_id), http_util.encodeURIComponent(sort_by), http_util.encodeURIComponent(sort_direction), http_util.encodeURIComponent(response_fields));
	})

	-- set HTTP verb
	req.headers:upsert(":method", "GET")
	-- TODO: create a function to select proper content-type
	--local var_accept = { "application/json" }
	req.headers:upsert("content-type", "application/json")

	-- api key in headers 'x-store-key'
	if self.api_key['x-store-key'] then
		req.headers:upsert("StoreKeyAuth", self.api_key['x-store-key'])
	end
	-- api key in headers 'x-api-key'
	if self.api_key['x-api-key'] then
		req.headers:upsert("ApiKeyAuth", self.api_key['x-api-key'])
	end

	-- make the HTTP call
	local headers, stream, errno = req:go()
	if not headers then
		return nil, stream, errno
	end
	local http_status = headers:get(":status")
	if http_status:sub(1,1) == "2" then
		local body, err, errno2 = stream:get_body_as_string()
		-- exception when getting the HTTP body
		if not body then
			return nil, err, errno2
		end
		stream:shutdown()
		local result, _, err3 = dkjson.decode(body)
		-- exception when decoding the HTTP body
		if result == nil then
			return nil, err3
		end
		return openapiclient_response_analytics_report_result.cast(result), headers
	else
		local body, err, errno2 = stream:get_body_as_string()
		if not body then
			return nil, err, errno2
		end
		stream:shutdown()
		-- return the error message (http body)
		return nil, http_status, body
	end
end

return {
	new = new_analytics_api;
}
