--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- analytics_metric class
local analytics_metric = {}
local analytics_metric_mt = {
	__name = "analytics_metric";
	__index = analytics_metric;
}

local function cast_analytics_metric(t)
	return setmetatable(t, analytics_metric_mt)
end

local function new_analytics_metric(orders_count, items_sold, gross_sales, net_sales, total_sales, avg_order_value, discounts, refunds, tax, shipping, fees, currency_id, additional_fields, custom_fields)
	return cast_analytics_metric({
		["orders_count"] = orders_count;
		["items_sold"] = items_sold;
		["gross_sales"] = gross_sales;
		["net_sales"] = net_sales;
		["total_sales"] = total_sales;
		["avg_order_value"] = avg_order_value;
		["discounts"] = discounts;
		["refunds"] = refunds;
		["tax"] = tax;
		["shipping"] = shipping;
		["fees"] = fees;
		["currency_id"] = currency_id;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_analytics_metric;
	new = new_analytics_metric;
}
