--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- analytics_period class
local analytics_period = {}
local analytics_period_mt = {
	__name = "analytics_period";
	__index = analytics_period;
}

local function cast_analytics_period(t)
	return setmetatable(t, analytics_period_mt)
end

local function new_analytics_period(date_from, date_to, additional_fields, custom_fields)
	return cast_analytics_period({
		["date_from"] = date_from;
		["date_to"] = date_to;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_analytics_period;
	new = new_analytics_period;
}
