--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- analytics_product_metric class
local analytics_product_metric = {}
local analytics_product_metric_mt = {
	__name = "analytics_product_metric";
	__index = analytics_product_metric;
}

local function cast_analytics_product_metric(t)
	return setmetatable(t, analytics_product_metric_mt)
end

local function new_analytics_product_metric(items_sold, orders_count, gross_sales, net_sales, discounts, refunds, currency_id, additional_fields, custom_fields)
	return cast_analytics_product_metric({
		["items_sold"] = items_sold;
		["orders_count"] = orders_count;
		["gross_sales"] = gross_sales;
		["net_sales"] = net_sales;
		["discounts"] = discounts;
		["refunds"] = refunds;
		["currency_id"] = currency_id;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_analytics_product_metric;
	new = new_analytics_product_metric;
}
