--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- carrier class
local carrier = {}
local carrier_mt = {
	__name = "carrier";
	__index = carrier;
}

local function cast_carrier(t)
	return setmetatable(t, carrier_mt)
end

local function new_carrier(id, name, active, shipping_methods, additional_fields, custom_fields)
	return cast_carrier({
		["id"] = id;
		["name"] = name;
		["active"] = active;
		["shipping_methods"] = shipping_methods;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_carrier;
	new = new_carrier;
}
