--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- cart_shipping_zone class
local cart_shipping_zone = {}
local cart_shipping_zone_mt = {
	__name = "cart_shipping_zone";
	__index = cart_shipping_zone;
}

local function cast_cart_shipping_zone(t)
	return setmetatable(t, cart_shipping_zone_mt)
end

local function new_cart_shipping_zone(id, code, name, country, country_iso2_codes, additional_fields, custom_fields)
	return cast_cart_shipping_zone({
		["id"] = id;
		["code"] = code;
		["name"] = name;
		["country"] = country;
		["country_iso2_codes"] = country_iso2_codes;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_cart_shipping_zone;
	new = new_cart_shipping_zone;
}
