--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- cart_create class
local cart_create = {}
local cart_create_mt = {
	__name = "cart_create";
	__index = cart_create;
}

local function cast_cart_create(t)
	return setmetatable(t, cart_create_mt)
end

local function new_cart_create(cart_id, store_url, bridge_url, store_root, store_key, shared_secret, validate_version, verify, db_tables_prefix, user_agent, ftp_host, ftp_user, ftp_password, ftp_port, ftp_store_dir, api_key_3dcart, admin_account, api_path, api_key_bigcommerce, client_id, access_token, context, access_token, api_key_shopify, api_password, access_token_shopify, api_key, api_username, encrypted_password, login, api_user_adnsf, api_pass, private_key, app_token, etsy_keystring, etsy_shared_secret, token_secret, etsy_client_id, etsy_refresh_token, ebay_client_id, ebay_client_secret, ebay_runame, ebay_access_token, ebay_refresh_token, ebay_environment, ebay_site_id, dw_client_id, dw_api_pass, demandware_user_name, demandware_user_password, store_id, seller_id, environment, hybris_client_id, hybris_client_secret, hybris_username, hybris_password, hybris_websites, walmart_client_id, walmart_client_secret, walmart_environment, walmart_channel_type, walmart_region, lightspeed_api_key, lightspeed_api_secret, shoplazza_access_token, shoplazza_shared_secret, shopware_access_key, shopware_api_key, shopware_api_secret, commercehq_api_key, commercehq_api_password, Var3dcart_private_key, Var3dcart_access_token, wc_consumer_key, wc_consumer_secret, magento_consumer_key, magento_consumer_secret, magento_access_token, magento_token_secret, prestashop_webservice_key, wix_app_id, wix_app_secret_key, wix_instance_id, wix_refresh_token, mercado_libre_app_id, mercado_libre_app_secret_key, mercado_libre_refresh_token, zid_client_id, zid_client_secret, zid_access_token, zid_authorization, zid_refresh_token, flipkart_client_id, flipkart_client_secret, allegro_client_id, allegro_client_secret, allegro_access_token, allegro_refresh_token, allegro_environment)
	return cast_cart_create({
		["cart_id"] = cart_id;
		["store_url"] = store_url;
		["bridge_url"] = bridge_url;
		["store_root"] = store_root;
		["store_key"] = store_key;
		["shared_secret"] = shared_secret;
		["validate_version"] = validate_version;
		["verify"] = verify;
		["db_tables_prefix"] = db_tables_prefix;
		["user_agent"] = user_agent;
		["ftp_host"] = ftp_host;
		["ftp_user"] = ftp_user;
		["ftp_password"] = ftp_password;
		["ftp_port"] = ftp_port;
		["ftp_store_dir"] = ftp_store_dir;
		["apiKey_3dcart"] = api_key_3dcart;
		["AdminAccount"] = admin_account;
		["ApiPath"] = api_path;
		["ApiKey_Bigcommerce"] = api_key_bigcommerce;
		["client_id"] = client_id;
		["accessToken"] = access_token;
		["context"] = context;
		["access_token"] = access_token;
		["apiKey_shopify"] = api_key_shopify;
		["apiPassword"] = api_password;
		["accessToken_shopify"] = access_token_shopify;
		["apiKey"] = api_key;
		["apiUsername"] = api_username;
		["EncryptedPassword"] = encrypted_password;
		["Login"] = login;
		["apiUser_adnsf"] = api_user_adnsf;
		["apiPass"] = api_pass;
		["privateKey"] = private_key;
		["appToken"] = app_token;
		["etsy_keystring"] = etsy_keystring;
		["etsy_shared_secret"] = etsy_shared_secret;
		["tokenSecret"] = token_secret;
		["etsy_client_id"] = etsy_client_id;
		["etsy_refresh_token"] = etsy_refresh_token;
		["ebay_client_id"] = ebay_client_id;
		["ebay_client_secret"] = ebay_client_secret;
		["ebay_runame"] = ebay_runame;
		["ebay_access_token"] = ebay_access_token;
		["ebay_refresh_token"] = ebay_refresh_token;
		["ebay_environment"] = ebay_environment;
		["ebay_site_id"] = ebay_site_id;
		["dw_client_id"] = dw_client_id;
		["dw_api_pass"] = dw_api_pass;
		["demandware_user_name"] = demandware_user_name;
		["demandware_user_password"] = demandware_user_password;
		["store_id"] = store_id;
		["seller_id"] = seller_id;
		["environment"] = environment;
		["hybris_client_id"] = hybris_client_id;
		["hybris_client_secret"] = hybris_client_secret;
		["hybris_username"] = hybris_username;
		["hybris_password"] = hybris_password;
		["hybris_websites"] = hybris_websites;
		["walmart_client_id"] = walmart_client_id;
		["walmart_client_secret"] = walmart_client_secret;
		["walmart_environment"] = walmart_environment;
		["walmart_channel_type"] = walmart_channel_type;
		["walmart_region"] = walmart_region;
		["lightspeed_api_key"] = lightspeed_api_key;
		["lightspeed_api_secret"] = lightspeed_api_secret;
		["shoplazza_access_token"] = shoplazza_access_token;
		["shoplazza_shared_secret"] = shoplazza_shared_secret;
		["shopware_access_key"] = shopware_access_key;
		["shopware_api_key"] = shopware_api_key;
		["shopware_api_secret"] = shopware_api_secret;
		["commercehq_api_key"] = commercehq_api_key;
		["commercehq_api_password"] = commercehq_api_password;
		["3dcart_private_key"] = Var3dcart_private_key;
		["3dcart_access_token"] = Var3dcart_access_token;
		["wc_consumer_key"] = wc_consumer_key;
		["wc_consumer_secret"] = wc_consumer_secret;
		["magento_consumer_key"] = magento_consumer_key;
		["magento_consumer_secret"] = magento_consumer_secret;
		["magento_access_token"] = magento_access_token;
		["magento_token_secret"] = magento_token_secret;
		["prestashop_webservice_key"] = prestashop_webservice_key;
		["wix_app_id"] = wix_app_id;
		["wix_app_secret_key"] = wix_app_secret_key;
		["wix_instance_id"] = wix_instance_id;
		["wix_refresh_token"] = wix_refresh_token;
		["mercado_libre_app_id"] = mercado_libre_app_id;
		["mercado_libre_app_secret_key"] = mercado_libre_app_secret_key;
		["mercado_libre_refresh_token"] = mercado_libre_refresh_token;
		["zid_client_id"] = zid_client_id;
		["zid_client_secret"] = zid_client_secret;
		["zid_access_token"] = zid_access_token;
		["zid_authorization"] = zid_authorization;
		["zid_refresh_token"] = zid_refresh_token;
		["flipkart_client_id"] = flipkart_client_id;
		["flipkart_client_secret"] = flipkart_client_secret;
		["allegro_client_id"] = allegro_client_id;
		["allegro_client_secret"] = allegro_client_secret;
		["allegro_access_token"] = allegro_access_token;
		["allegro_refresh_token"] = allegro_refresh_token;
		["allegro_environment"] = allegro_environment;
	})
end

return {
	cast = cast_cart_create;
	new = new_cart_create;
}
