--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- cart_shipping_method_rate class
local cart_shipping_method_rate = {}
local cart_shipping_method_rate_mt = {
	__name = "cart_shipping_method_rate";
	__index = cart_shipping_method_rate;
}

local function cast_cart_shipping_method_rate(t)
	return setmetatable(t, cart_shipping_method_rate_mt)
end

local function new_cart_shipping_method_rate(min_weight, max_weight, min_order_amount, max_order_amount, min_items_count, max_items_count, price, additional_fields, custom_fields)
	return cast_cart_shipping_method_rate({
		["min_weight"] = min_weight;
		["max_weight"] = max_weight;
		["min_order_amount"] = min_order_amount;
		["max_order_amount"] = max_order_amount;
		["min_items_count"] = min_items_count;
		["max_items_count"] = max_items_count;
		["price"] = price;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_cart_shipping_method_rate;
	new = new_cart_shipping_method_rate;
}
