--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- category class
local category = {}
local category_mt = {
	__name = "category";
	__index = category;
}

local function cast_category(t)
	return setmetatable(t, category_mt)
end

local function new_category(id, parent_id, created_at, modified_at, name, short_description, description, stores_ids, keywords, meta_description, meta_title, avail, path, seo_url, sort_order, images, additional_fields, custom_fields)
	return cast_category({
		["id"] = id;
		["parent_id"] = parent_id;
		["created_at"] = created_at;
		["modified_at"] = modified_at;
		["name"] = name;
		["short_description"] = short_description;
		["description"] = description;
		["stores_ids"] = stores_ids;
		["keywords"] = keywords;
		["meta_description"] = meta_description;
		["meta_title"] = meta_title;
		["avail"] = avail;
		["path"] = path;
		["seo_url"] = seo_url;
		["sort_order"] = sort_order;
		["images"] = images;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_category;
	new = new_category;
}
