--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- child class
local child = {}
local child_mt = {
	__name = "child";
	__index = child;
}

local function cast_child(t)
	return setmetatable(t, child_mt)
end

local function new_child(id, parent_id, sku, upc, ean, mpn, gtin, isbn, url, seo_url, sort_order, created_time, modified_time, name, short_description, full_description, images, combination, default_price, cost_price, unit_price, measure_unit, list_price, wholesale_price, advanced_price, tax_class_id, avail_for_sale, allow_backorders, in_stock, on_sale, manage_stock, inventory_level, inventory, min_quantity, low_stock_threshold, default_qty_in_pack, is_qty_in_pack_fixed, weight_unit, weight, dimensions_unit, width, height, length, meta_title, meta_description, meta_keywords, discounts, is_virtual, additional_fields, custom_fields)
	return cast_child({
		["id"] = id;
		["parent_id"] = parent_id;
		["sku"] = sku;
		["upc"] = upc;
		["ean"] = ean;
		["mpn"] = mpn;
		["gtin"] = gtin;
		["isbn"] = isbn;
		["url"] = url;
		["seo_url"] = seo_url;
		["sort_order"] = sort_order;
		["created_time"] = created_time;
		["modified_time"] = modified_time;
		["name"] = name;
		["short_description"] = short_description;
		["full_description"] = full_description;
		["images"] = images;
		["combination"] = combination;
		["default_price"] = default_price;
		["cost_price"] = cost_price;
		["unit_price"] = unit_price;
		["measure_unit"] = measure_unit;
		["list_price"] = list_price;
		["wholesale_price"] = wholesale_price;
		["advanced_price"] = advanced_price;
		["tax_class_id"] = tax_class_id;
		["avail_for_sale"] = avail_for_sale;
		["allow_backorders"] = allow_backorders;
		["in_stock"] = in_stock;
		["on_sale"] = on_sale;
		["manage_stock"] = manage_stock;
		["inventory_level"] = inventory_level;
		["inventory"] = inventory;
		["min_quantity"] = min_quantity;
		["low_stock_threshold"] = low_stock_threshold;
		["default_qty_in_pack"] = default_qty_in_pack;
		["is_qty_in_pack_fixed"] = is_qty_in_pack_fixed;
		["weight_unit"] = weight_unit;
		["weight"] = weight;
		["dimensions_unit"] = dimensions_unit;
		["width"] = width;
		["height"] = height;
		["length"] = length;
		["meta_title"] = meta_title;
		["meta_description"] = meta_description;
		["meta_keywords"] = meta_keywords;
		["discounts"] = discounts;
		["is_virtual"] = is_virtual;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_child;
	new = new_child;
}
