--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- coupon_history class
local coupon_history = {}
local coupon_history_mt = {
	__name = "coupon_history";
	__index = coupon_history;
}

local function cast_coupon_history(t)
	return setmetatable(t, coupon_history_mt)
end

local function new_coupon_history(order_id, amount, additional_fields, custom_fields)
	return cast_coupon_history({
		["order_id"] = order_id;
		["amount"] = amount;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_coupon_history;
	new = new_coupon_history;
}
