--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- customer_attribute class
local customer_attribute = {}
local customer_attribute_mt = {
	__name = "customer_attribute";
	__index = customer_attribute;
}

local function cast_customer_attribute(t)
	return setmetatable(t, customer_attribute_mt)
end

local function new_customer_attribute(attribute_id, code, name, type, values, additional_fields, custom_fields)
	return cast_customer_attribute({
		["attribute_id"] = attribute_id;
		["code"] = code;
		["name"] = name;
		["type"] = type;
		["values"] = values;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_customer_attribute;
	new = new_customer_attribute;
}
