--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- gift_card class
local gift_card = {}
local gift_card_mt = {
	__name = "gift_card";
	__index = gift_card;
}

local function cast_gift_card(t)
	return setmetatable(t, gift_card_mt)
end

local function new_gift_card(id, code, name, type, currency_code, amount, initial_amount, status, created_at, avail_to, free_product_ids, message, issuer_email, recipient_email, issuer_name, recipient_name, usage_history, additional_fields, custom_fields)
	return cast_gift_card({
		["id"] = id;
		["code"] = code;
		["name"] = name;
		["type"] = type;
		["currency_code"] = currency_code;
		["amount"] = amount;
		["initial_amount"] = initial_amount;
		["status"] = status;
		["created_at"] = created_at;
		["avail_to"] = avail_to;
		["free_product_ids"] = free_product_ids;
		["message"] = message;
		["issuer_email"] = issuer_email;
		["recipient_email"] = recipient_email;
		["issuer_name"] = issuer_name;
		["recipient_name"] = recipient_name;
		["usage_history"] = usage_history;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_gift_card;
	new = new_gift_card;
}
