--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- image class
local image = {}
local image_mt = {
	__name = "image";
	__index = image;
}

local function cast_image(t)
	return setmetatable(t, image_mt)
end

local function new_image(id, http_path, file_name, mime_type, size, create_at, modified_at, alt, avail, sort_order, type, additional_fields, custom_fields)
	return cast_image({
		["id"] = id;
		["http_path"] = http_path;
		["file_name"] = file_name;
		["mime-type"] = mime_type;
		["size"] = size;
		["create_at"] = create_at;
		["modified_at"] = modified_at;
		["alt"] = alt;
		["avail"] = avail;
		["sort_order"] = sort_order;
		["type"] = type;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_image;
	new = new_image;
}
