--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- info class
local info = {}
local info_mt = {
	__name = "info";
	__index = info;
}

local function cast_info(t)
	return setmetatable(t, info_mt)
end

local function new_info(owner, country, state, state_code, city, street_address, street_address_line_2, zip_code, email, phone, additional_fields, custom_fields)
	return cast_info({
		["owner"] = owner;
		["country"] = country;
		["state"] = state;
		["state_code"] = state_code;
		["city"] = city;
		["street_address"] = street_address;
		["street_address_line_2"] = street_address_line_2;
		["zip_code"] = zip_code;
		["email"] = email;
		["phone"] = phone;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_info;
	new = new_info;
}
