--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- marketplace_product class
local marketplace_product = {}
local marketplace_product_mt = {
	__name = "marketplace_product";
	__index = marketplace_product;
}

local function cast_marketplace_product(t)
	return setmetatable(t, marketplace_product_mt)
end

local function new_marketplace_product(id, type, u_asin, u_ean, u_gtin, u_isbn, u_mpn, u_upc, name, description, url, price, images, product_options, manufacturer, brand, weight, weight_unit, dimensions_unit, width, height, length, additional_fields, custom_fields)
	return cast_marketplace_product({
		["id"] = id;
		["type"] = type;
		["u_asin"] = u_asin;
		["u_ean"] = u_ean;
		["u_gtin"] = u_gtin;
		["u_isbn"] = u_isbn;
		["u_mpn"] = u_mpn;
		["u_upc"] = u_upc;
		["name"] = name;
		["description"] = description;
		["url"] = url;
		["price"] = price;
		["images"] = images;
		["product_options"] = product_options;
		["manufacturer"] = manufacturer;
		["brand"] = brand;
		["weight"] = weight;
		["weight_unit"] = weight_unit;
		["dimensions_unit"] = dimensions_unit;
		["width"] = width;
		["height"] = height;
		["length"] = length;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_marketplace_product;
	new = new_marketplace_product;
}
