--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- model_response_category_unassign class
local model_response_category_unassign = {}
local model_response_category_unassign_mt = {
	__name = "model_response_category_unassign";
	__index = model_response_category_unassign;
}

local function cast_model_response_category_unassign(t)
	return setmetatable(t, model_response_category_unassign_mt)
end

local function new_model_response_category_unassign(return_code, return_message, result, additional_fields, custom_fields)
	return cast_model_response_category_unassign({
		["return_code"] = return_code;
		["return_message"] = return_message;
		["result"] = result;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_model_response_category_unassign;
	new = new_model_response_category_unassign;
}
