--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- order_status_refund class
local order_status_refund = {}
local order_status_refund_mt = {
	__name = "order_status_refund";
	__index = order_status_refund;
}

local function cast_order_status_refund(t)
	return setmetatable(t, order_status_refund_mt)
end

local function new_order_status_refund(shipping, fee, tax, total_refunded, time, comment, refunded_items, additional_fields, custom_fields)
	return cast_order_status_refund({
		["shipping"] = shipping;
		["fee"] = fee;
		["tax"] = tax;
		["total_refunded"] = total_refunded;
		["time"] = time;
		["comment"] = comment;
		["refunded_items"] = refunded_items;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_order_status_refund;
	new = new_order_status_refund;
}
