--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- order_return_update_order_products_inner class
local order_return_update_order_products_inner = {}
local order_return_update_order_products_inner_mt = {
	__name = "order_return_update_order_products_inner";
	__index = order_return_update_order_products_inner;
}

local function cast_order_return_update_order_products_inner(t)
	return setmetatable(t, order_return_update_order_products_inner_mt)
end

local function new_order_return_update_order_products_inner(order_product_id, order_product_quantity, order_product_status, order_product_action_id)
	return cast_order_return_update_order_products_inner({
		["order_product_id"] = order_product_id;
		["order_product_quantity"] = order_product_quantity;
		["order_product_status"] = order_product_status;
		["order_product_action_id"] = order_product_action_id;
	})
end

return {
	cast = cast_order_return_update_order_products_inner;
	new = new_order_return_update_order_products_inner;
}
