--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- order_calculate_shipping_rate class
local order_calculate_shipping_rate = {}
local order_calculate_shipping_rate_mt = {
	__name = "order_calculate_shipping_rate";
	__index = order_calculate_shipping_rate;
}

local function cast_order_calculate_shipping_rate(t)
	return setmetatable(t, order_calculate_shipping_rate_mt)
end

local function new_order_calculate_shipping_rate(code, name, price, price_inc_tax, tax, tax_rate, additional_fields, custom_fields)
	return cast_order_calculate_shipping_rate({
		["code"] = code;
		["name"] = name;
		["price"] = price;
		["price_inc_tax"] = price_inc_tax;
		["tax"] = tax;
		["tax_rate"] = tax_rate;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_order_calculate_shipping_rate;
	new = new_order_calculate_shipping_rate;
}
