--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- order_calculate_discount class
local order_calculate_discount = {}
local order_calculate_discount_mt = {
	__name = "order_calculate_discount";
	__index = order_calculate_discount;
}

local function cast_order_calculate_discount(t)
	return setmetatable(t, order_calculate_discount_mt)
end

local function new_order_calculate_discount(code, value, type, free_shipping, additional_fields, custom_fields)
	return cast_order_calculate_discount({
		["code"] = code;
		["value"] = value;
		["type"] = type;
		["free_shipping"] = free_shipping;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_order_calculate_discount;
	new = new_order_calculate_discount;
}
