--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- order_shipment_add class
local order_shipment_add = {}
local order_shipment_add_mt = {
	__name = "order_shipment_add";
	__index = order_shipment_add;
}

local function cast_order_shipment_add(t)
	return setmetatable(t, order_shipment_add_mt)
end

local function new_order_shipment_add(order_id, warehouse_id, store_id, shipment_provider, shipping_method, items, tracking_numbers, tracking_link, is_shipped, send_notifications, adjust_stock, enable_cache, check_process_status, tracking_provider, use_latest_api_version)
	return cast_order_shipment_add({
		["order_id"] = order_id;
		["warehouse_id"] = warehouse_id;
		["store_id"] = store_id;
		["shipment_provider"] = shipment_provider;
		["shipping_method"] = shipping_method;
		["items"] = items;
		["tracking_numbers"] = tracking_numbers;
		["tracking_link"] = tracking_link;
		["is_shipped"] = is_shipped;
		["send_notifications"] = send_notifications;
		["adjust_stock"] = adjust_stock;
		["enable_cache"] = enable_cache;
		["check_process_status"] = check_process_status;
		["tracking_provider"] = tracking_provider;
		["use_latest_api_version"] = use_latest_api_version;
	})
end

return {
	cast = cast_order_shipment_add;
	new = new_order_shipment_add;
}
