--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- order_item class
local order_item = {}
local order_item_mt = {
	__name = "order_item";
	__index = order_item;
}

local function cast_order_item(t)
	return setmetatable(t, order_item_mt)
end

local function new_order_item(product_id, order_product_id, model, name, price, price_inc_tax, quantity, discount_amount, total_price, tax_percent, tax_value, tax_value_after_discount, options, variant_id, weight_unit, weight, barcode, parent_order_product_id, additional_fields, custom_fields)
	return cast_order_item({
		["product_id"] = product_id;
		["order_product_id"] = order_product_id;
		["model"] = model;
		["name"] = name;
		["price"] = price;
		["price_inc_tax"] = price_inc_tax;
		["quantity"] = quantity;
		["discount_amount"] = discount_amount;
		["total_price"] = total_price;
		["tax_percent"] = tax_percent;
		["tax_value"] = tax_value;
		["tax_value_after_discount"] = tax_value_after_discount;
		["options"] = options;
		["variant_id"] = variant_id;
		["weight_unit"] = weight_unit;
		["weight"] = weight;
		["barcode"] = barcode;
		["parent_order_product_id"] = parent_order_product_id;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_order_item;
	new = new_order_item;
}
