--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- order_preestimate_shipping_list class
local order_preestimate_shipping_list = {}
local order_preestimate_shipping_list_mt = {
	__name = "order_preestimate_shipping_list";
	__index = order_preestimate_shipping_list;
}

local function cast_order_preestimate_shipping_list(t)
	return setmetatable(t, order_preestimate_shipping_list_mt)
end

local function new_order_preestimate_shipping_list(warehouse_id, customer_id, customer_email, store_id, shipp_address_1, shipp_city, shipp_postcode, shipp_state, shipp_country, params, exclude, idempotency_key, order_item)
	return cast_order_preestimate_shipping_list({
		["warehouse_id"] = warehouse_id;
		["customer_id"] = customer_id;
		["customer_email"] = customer_email;
		["store_id"] = store_id;
		["shipp_address_1"] = shipp_address_1;
		["shipp_city"] = shipp_city;
		["shipp_postcode"] = shipp_postcode;
		["shipp_state"] = shipp_state;
		["shipp_country"] = shipp_country;
		["params"] = params;
		["exclude"] = exclude;
		["idempotency_key"] = idempotency_key;
		["order_item"] = order_item;
	})
end

return {
	cast = cast_order_preestimate_shipping_list;
	new = new_order_preestimate_shipping_list;
}
