--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- param_definition_filtering_conditions_filter_rule_value class
local param_definition_filtering_conditions_filter_rule_value = {}
local param_definition_filtering_conditions_filter_rule_value_mt = {
	__name = "param_definition_filtering_conditions_filter_rule_value";
	__index = param_definition_filtering_conditions_filter_rule_value;
}

local function cast_param_definition_filtering_conditions_filter_rule_value(t)
	return setmetatable(t, param_definition_filtering_conditions_filter_rule_value_mt)
end

local function new_param_definition_filtering_conditions_filter_rule_value()
	return cast_param_definition_filtering_conditions_filter_rule_value({
	})
end

return {
	cast = cast_param_definition_filtering_conditions_filter_rule_value;
	new = new_param_definition_filtering_conditions_filter_rule_value;
}
