--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- plugin_list class
local plugin_list = {}
local plugin_list_mt = {
	__name = "plugin_list";
	__index = plugin_list;
}

local function cast_plugin_list(t)
	return setmetatable(t, plugin_list_mt)
end

local function new_plugin_list(all_plugins, plugins, additional_fields, custom_fields)
	return cast_plugin_list({
		["all_plugins"] = all_plugins;
		["plugins"] = plugins;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_plugin_list;
	new = new_plugin_list;
}
