--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_price_update class
local product_price_update = {}
local product_price_update_mt = {
	__name = "product_price_update";
	__index = product_price_update;
}

local function cast_product_price_update(t)
	return setmetatable(t, product_price_update_mt)
end

local function new_product_price_update(product_id, group_prices, idempotency_key)
	return cast_product_price_update({
		["product_id"] = product_id;
		["group_prices"] = group_prices;
		["idempotency_key"] = idempotency_key;
	})
end

return {
	cast = cast_product_price_update;
	new = new_product_price_update;
}
