--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_variant_add_batch_payload_inner class
local product_variant_add_batch_payload_inner = {}
local product_variant_add_batch_payload_inner_mt = {
	__name = "product_variant_add_batch_payload_inner";
	__index = product_variant_add_batch_payload_inner;
}

local function cast_product_variant_add_batch_payload_inner(t)
	return setmetatable(t, product_variant_add_batch_payload_inner_mt)
end

local function new_product_variant_add_batch_payload_inner(product_id, combination, name, description, short_description, sku, model, price, old_price, cost_price, special_price, sprice_create, sprice_expire, advanced_prices, meta_title, meta_description, meta_keywords, categories_ids, stores_ids, weight, width, height, length, weight_unit, warehouse_id, quantity, manage_stock, in_stock, store_id, lang_id, tax_class_id, backorder_status, status, visible, is_virtual, downloadable, is_default, upc, isbn, mpn, ean, barcode, available_for_sale, is_free_shipping, taxable, seo_url, manufacturer_id, harmonized_system_code, marketplace_item_properties, images, product_images_ids, related_products_ids, up_sell_products_ids, cross_sell_products_ids)
	return cast_product_variant_add_batch_payload_inner({
		["product_id"] = product_id;
		["combination"] = combination;
		["name"] = name;
		["description"] = description;
		["short_description"] = short_description;
		["sku"] = sku;
		["model"] = model;
		["price"] = price;
		["old_price"] = old_price;
		["cost_price"] = cost_price;
		["special_price"] = special_price;
		["sprice_create"] = sprice_create;
		["sprice_expire"] = sprice_expire;
		["advanced_prices"] = advanced_prices;
		["meta_title"] = meta_title;
		["meta_description"] = meta_description;
		["meta_keywords"] = meta_keywords;
		["categories_ids"] = categories_ids;
		["stores_ids"] = stores_ids;
		["weight"] = weight;
		["width"] = width;
		["height"] = height;
		["length"] = length;
		["weight_unit"] = weight_unit;
		["warehouse_id"] = warehouse_id;
		["quantity"] = quantity;
		["manage_stock"] = manage_stock;
		["in_stock"] = in_stock;
		["store_id"] = store_id;
		["lang_id"] = lang_id;
		["tax_class_id"] = tax_class_id;
		["backorder_status"] = backorder_status;
		["status"] = status;
		["visible"] = visible;
		["is_virtual"] = is_virtual;
		["downloadable"] = downloadable;
		["is_default"] = is_default;
		["upc"] = upc;
		["isbn"] = isbn;
		["mpn"] = mpn;
		["ean"] = ean;
		["barcode"] = barcode;
		["available_for_sale"] = available_for_sale;
		["is_free_shipping"] = is_free_shipping;
		["taxable"] = taxable;
		["seo_url"] = seo_url;
		["manufacturer_id"] = manufacturer_id;
		["harmonized_system_code"] = harmonized_system_code;
		["marketplace_item_properties"] = marketplace_item_properties;
		["images"] = images;
		["product_images_ids"] = product_images_ids;
		["related_products_ids"] = related_products_ids;
		["up_sell_products_ids"] = up_sell_products_ids;
		["cross_sell_products_ids"] = cross_sell_products_ids;
	})
end

return {
	cast = cast_product_variant_add_batch_payload_inner;
	new = new_product_variant_add_batch_payload_inner;
}
