--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_add_specifics_inner_food_details class
local product_add_specifics_inner_food_details = {}
local product_add_specifics_inner_food_details_mt = {
	__name = "product_add_specifics_inner_food_details";
	__index = product_add_specifics_inner_food_details;
}

local function cast_product_add_specifics_inner_food_details(t)
	return setmetatable(t, product_add_specifics_inner_food_details_mt)
end

local function new_product_add_specifics_inner_food_details(calories)
	return cast_product_add_specifics_inner_food_details({
		["calories"] = calories;
	})
end

return {
	cast = cast_product_add_specifics_inner_food_details;
	new = new_product_add_specifics_inner_food_details;
}
