--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_variant_update_batch class
local product_variant_update_batch = {}
local product_variant_update_batch_mt = {
	__name = "product_variant_update_batch";
	__index = product_variant_update_batch;
}

local function cast_product_variant_update_batch(t)
	return setmetatable(t, product_variant_update_batch_mt)
end

local function new_product_variant_update_batch(nested_items_update_behaviour, clear_cache, reindex, payload, idempotency_key)
	return cast_product_variant_update_batch({
		["nested_items_update_behaviour"] = nested_items_update_behaviour;
		["clear_cache"] = clear_cache;
		["reindex"] = reindex;
		["payload"] = payload;
		["idempotency_key"] = idempotency_key;
	})
end

return {
	cast = cast_product_variant_update_batch;
	new = new_product_variant_update_batch;
}
