--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_add class
local product_add = {}
local product_add_mt = {
	__name = "product_add";
	__index = product_add;
}

local function cast_product_add(t)
	return setmetatable(t, product_add_mt)
end

local function new_product_add(name, model, sku, description, price, old_price, special_price, cost_price, fixed_cost_shipping_price, sprice_create, sprice_modified, sprice_expire, tier_prices, group_prices, available_for_view, available_for_sale, weight, width, height, length, weight_unit, dimensions_unit, short_description, warehouse_id, backorder_status, quantity, downloadable, wholesale_price, created_at, manufacturer, manufacturer_id, categories_ids, related_products_ids, up_sell_products_ids, cross_sell_products_ids, tax_class_id, type, meta_title, meta_keywords, meta_description, url, lang_id, stores_ids, category_id, viewed_count, ordered_count, attribute_set_name, attribute_name, shipping_template_id, production_partner_ids, condition, listing_duration, listing_type, payment_methods, return_accepted, shipping_details, paypal_email, seller_profiles, package_details, best_offer, sales_tax, barcode, upc, ean, isbn, specifics, image_url, image_name, reserve_price, buyitnow_price, condition_description, auction_confidentiality_level, avail_from, tags, clear_cache, asin, gtin, mpn, taxable, visible, status, seo_url, product_class, product_type, marketplace_item_properties, manage_stock, harmonized_system_code, country_of_origin, files, search_keywords, store_id, brand_name, is_virtual, is_free_shipping, in_stock, delivery_code, product_reference, delivery_type, delivery_time, size_chart, certifications, delivery_option_ids, manufacturer_info, when_made, is_supply, materials, auto_renew, allow_display_condition, min_order_quantity, max_order_quantity)
	return cast_product_add({
		["name"] = name;
		["model"] = model;
		["sku"] = sku;
		["description"] = description;
		["price"] = price;
		["old_price"] = old_price;
		["special_price"] = special_price;
		["cost_price"] = cost_price;
		["fixed_cost_shipping_price"] = fixed_cost_shipping_price;
		["sprice_create"] = sprice_create;
		["sprice_modified"] = sprice_modified;
		["sprice_expire"] = sprice_expire;
		["tier_prices"] = tier_prices;
		["group_prices"] = group_prices;
		["available_for_view"] = available_for_view;
		["available_for_sale"] = available_for_sale;
		["weight"] = weight;
		["width"] = width;
		["height"] = height;
		["length"] = length;
		["weight_unit"] = weight_unit;
		["dimensions_unit"] = dimensions_unit;
		["short_description"] = short_description;
		["warehouse_id"] = warehouse_id;
		["backorder_status"] = backorder_status;
		["quantity"] = quantity;
		["downloadable"] = downloadable;
		["wholesale_price"] = wholesale_price;
		["created_at"] = created_at;
		["manufacturer"] = manufacturer;
		["manufacturer_id"] = manufacturer_id;
		["categories_ids"] = categories_ids;
		["related_products_ids"] = related_products_ids;
		["up_sell_products_ids"] = up_sell_products_ids;
		["cross_sell_products_ids"] = cross_sell_products_ids;
		["tax_class_id"] = tax_class_id;
		["type"] = type;
		["meta_title"] = meta_title;
		["meta_keywords"] = meta_keywords;
		["meta_description"] = meta_description;
		["url"] = url;
		["lang_id"] = lang_id;
		["stores_ids"] = stores_ids;
		["category_id"] = category_id;
		["viewed_count"] = viewed_count;
		["ordered_count"] = ordered_count;
		["attribute_set_name"] = attribute_set_name;
		["attribute_name"] = attribute_name;
		["shipping_template_id"] = shipping_template_id;
		["production_partner_ids"] = production_partner_ids;
		["condition"] = condition;
		["listing_duration"] = listing_duration;
		["listing_type"] = listing_type;
		["payment_methods"] = payment_methods;
		["return_accepted"] = return_accepted;
		["shipping_details"] = shipping_details;
		["paypal_email"] = paypal_email;
		["seller_profiles"] = seller_profiles;
		["package_details"] = package_details;
		["best_offer"] = best_offer;
		["sales_tax"] = sales_tax;
		["barcode"] = barcode;
		["upc"] = upc;
		["ean"] = ean;
		["isbn"] = isbn;
		["specifics"] = specifics;
		["image_url"] = image_url;
		["image_name"] = image_name;
		["reserve_price"] = reserve_price;
		["buyitnow_price"] = buyitnow_price;
		["condition_description"] = condition_description;
		["auction_confidentiality_level"] = auction_confidentiality_level;
		["avail_from"] = avail_from;
		["tags"] = tags;
		["clear_cache"] = clear_cache;
		["asin"] = asin;
		["gtin"] = gtin;
		["mpn"] = mpn;
		["taxable"] = taxable;
		["visible"] = visible;
		["status"] = status;
		["seo_url"] = seo_url;
		["product_class"] = product_class;
		["product_type"] = product_type;
		["marketplace_item_properties"] = marketplace_item_properties;
		["manage_stock"] = manage_stock;
		["harmonized_system_code"] = harmonized_system_code;
		["country_of_origin"] = country_of_origin;
		["files"] = files;
		["search_keywords"] = search_keywords;
		["store_id"] = store_id;
		["brand_name"] = brand_name;
		["is_virtual"] = is_virtual;
		["is_free_shipping"] = is_free_shipping;
		["in_stock"] = in_stock;
		["delivery_code"] = delivery_code;
		["product_reference"] = product_reference;
		["delivery_type"] = delivery_type;
		["delivery_time"] = delivery_time;
		["size_chart"] = size_chart;
		["certifications"] = certifications;
		["delivery_option_ids"] = delivery_option_ids;
		["manufacturer_info"] = manufacturer_info;
		["when_made"] = when_made;
		["is_supply"] = is_supply;
		["materials"] = materials;
		["auto_renew"] = auto_renew;
		["allow_display_condition"] = allow_display_condition;
		["min_order_quantity"] = min_order_quantity;
		["max_order_quantity"] = max_order_quantity;
	})
end

return {
	cast = cast_product_add;
	new = new_product_add;
}
