--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_variant_add class
local product_variant_add = {}
local product_variant_add_mt = {
	__name = "product_variant_add";
	__index = product_variant_add;
}

local function cast_product_variant_add(t)
	return setmetatable(t, product_variant_add_mt)
end

local function new_product_variant_add(product_id, name, model, sku, barcode, gtin, price, old_price, cost_price, fixed_cost_shipping_price, attributes, description, special_price, sprice_create, sprice_modified, sprice_expire, available_for_view, available_for_sale, weight, width, height, length, weight_unit, short_description, warehouse_id, quantity, created_at, manufacturer, tax_class_id, meta_title, meta_keywords, meta_description, url, store_id, lang_id, clear_cache, taxable, harmonized_system_code, country_of_origin, manage_stock, upc, mpn, ean, isbn, stores_ids, is_default, is_free_shipping, marketplace_item_properties, in_stock, backorder_status, tier_prices, is_virtual)
	return cast_product_variant_add({
		["product_id"] = product_id;
		["name"] = name;
		["model"] = model;
		["sku"] = sku;
		["barcode"] = barcode;
		["gtin"] = gtin;
		["price"] = price;
		["old_price"] = old_price;
		["cost_price"] = cost_price;
		["fixed_cost_shipping_price"] = fixed_cost_shipping_price;
		["attributes"] = attributes;
		["description"] = description;
		["special_price"] = special_price;
		["sprice_create"] = sprice_create;
		["sprice_modified"] = sprice_modified;
		["sprice_expire"] = sprice_expire;
		["available_for_view"] = available_for_view;
		["available_for_sale"] = available_for_sale;
		["weight"] = weight;
		["width"] = width;
		["height"] = height;
		["length"] = length;
		["weight_unit"] = weight_unit;
		["short_description"] = short_description;
		["warehouse_id"] = warehouse_id;
		["quantity"] = quantity;
		["created_at"] = created_at;
		["manufacturer"] = manufacturer;
		["tax_class_id"] = tax_class_id;
		["meta_title"] = meta_title;
		["meta_keywords"] = meta_keywords;
		["meta_description"] = meta_description;
		["url"] = url;
		["store_id"] = store_id;
		["lang_id"] = lang_id;
		["clear_cache"] = clear_cache;
		["taxable"] = taxable;
		["harmonized_system_code"] = harmonized_system_code;
		["country_of_origin"] = country_of_origin;
		["manage_stock"] = manage_stock;
		["upc"] = upc;
		["mpn"] = mpn;
		["ean"] = ean;
		["isbn"] = isbn;
		["stores_ids"] = stores_ids;
		["is_default"] = is_default;
		["is_free_shipping"] = is_free_shipping;
		["marketplace_item_properties"] = marketplace_item_properties;
		["in_stock"] = in_stock;
		["backorder_status"] = backorder_status;
		["tier_prices"] = tier_prices;
		["is_virtual"] = is_virtual;
	})
end

return {
	cast = cast_product_variant_add;
	new = new_product_variant_add;
}
