--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_variant_delete_batch_payload_inner class
local product_variant_delete_batch_payload_inner = {}
local product_variant_delete_batch_payload_inner_mt = {
	__name = "product_variant_delete_batch_payload_inner";
	__index = product_variant_delete_batch_payload_inner;
}

local function cast_product_variant_delete_batch_payload_inner(t)
	return setmetatable(t, product_variant_delete_batch_payload_inner_mt)
end

local function new_product_variant_delete_batch_payload_inner(product_id, id, store_id)
	return cast_product_variant_delete_batch_payload_inner({
		["product_id"] = product_id;
		["id"] = id;
		["store_id"] = store_id;
	})
end

return {
	cast = cast_product_variant_delete_batch_payload_inner;
	new = new_product_variant_delete_batch_payload_inner;
}
