--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_add_size_chart class
local product_add_size_chart = {}
local product_add_size_chart_mt = {
	__name = "product_add_size_chart";
	__index = product_add_size_chart;
}

local function cast_product_add_size_chart(t)
	return setmetatable(t, product_add_size_chart_mt)
end

local function new_product_add_size_chart(id, url)
	return cast_product_add_size_chart({
		["id"] = id;
		["url"] = url;
	})
end

return {
	cast = cast_product_add_size_chart;
	new = new_product_add_size_chart;
}
