--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_variant_price_add class
local product_variant_price_add = {}
local product_variant_price_add_mt = {
	__name = "product_variant_price_add";
	__index = product_variant_price_add;
}

local function cast_product_variant_price_add(t)
	return setmetatable(t, product_variant_price_add_mt)
end

local function new_product_variant_price_add(id, product_id, group_prices, store_id)
	return cast_product_variant_price_add({
		["id"] = id;
		["product_id"] = product_id;
		["group_prices"] = group_prices;
		["store_id"] = store_id;
	})
end

return {
	cast = cast_product_variant_price_add;
	new = new_product_variant_price_add;
}
