--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_price_update_group_prices_inner class
local product_price_update_group_prices_inner = {}
local product_price_update_group_prices_inner_mt = {
	__name = "product_price_update_group_prices_inner";
	__index = product_price_update_group_prices_inner;
}

local function cast_product_price_update_group_prices_inner(t)
	return setmetatable(t, product_price_update_group_prices_inner_mt)
end

local function new_product_price_update_group_prices_inner(id, group_id, price, qty)
	return cast_product_price_update_group_prices_inner({
		["id"] = id;
		["group_id"] = group_id;
		["price"] = price;
		["qty"] = qty;
	})
end

return {
	cast = cast_product_price_update_group_prices_inner;
	new = new_product_price_update_group_prices_inner;
}
