--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_add_logistic_info_inner class
local product_add_logistic_info_inner = {}
local product_add_logistic_info_inner_mt = {
	__name = "product_add_logistic_info_inner";
	__index = product_add_logistic_info_inner;
}

local function cast_product_add_logistic_info_inner(t)
	return setmetatable(t, product_add_logistic_info_inner_mt)
end

local function new_product_add_logistic_info_inner(logistic_id, is_free, shipping_fee, size_id)
	return cast_product_add_logistic_info_inner({
		["logistic_id"] = logistic_id;
		["is_free"] = is_free;
		["shipping_fee"] = shipping_fee;
		["size_id"] = size_id;
	})
end

return {
	cast = cast_product_add_logistic_info_inner;
	new = new_product_add_logistic_info_inner;
}
