--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_review_rating class
local product_review_rating = {}
local product_review_rating_mt = {
	__name = "product_review_rating";
	__index = product_review_rating;
}

local function cast_product_review_rating(t)
	return setmetatable(t, product_review_rating_mt)
end

local function new_product_review_rating(id, name, value, additional_fields, custom_fields)
	return cast_product_review_rating({
		["id"] = id;
		["name"] = name;
		["value"] = value;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_product_review_rating;
	new = new_product_review_rating;
}
