--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_add_shipping_details_inner class
local product_add_shipping_details_inner = {}
local product_add_shipping_details_inner_mt = {
	__name = "product_add_shipping_details_inner";
	__index = product_add_shipping_details_inner;
}

local function cast_product_add_shipping_details_inner(t)
	return setmetatable(t, product_add_shipping_details_inner_mt)
end

local function new_product_add_shipping_details_inner(shipping_type, shipping_service, shipping_cost)
	return cast_product_add_shipping_details_inner({
		["shipping_type"] = shipping_type;
		["shipping_service"] = shipping_service;
		["shipping_cost"] = shipping_cost;
	})
end

return {
	cast = cast_product_add_shipping_details_inner;
	new = new_product_add_shipping_details_inner;
}
