--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_option_add_values_inner class
local product_option_add_values_inner = {}
local product_option_add_values_inner_mt = {
	__name = "product_option_add_values_inner";
	__index = product_option_add_values_inner;
}

local function cast_product_option_add_values_inner(t)
	return setmetatable(t, product_option_add_values_inner_mt)
end

local function new_product_option_add_values_inner(value, display_value, is_default)
	return cast_product_option_add_values_inner({
		["value"] = value;
		["display_value"] = display_value;
		["is_default"] = is_default;
	})
end

return {
	cast = cast_product_option_add_values_inner;
	new = new_product_option_add_values_inner;
}
