--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_variant_delete_batch class
local product_variant_delete_batch = {}
local product_variant_delete_batch_mt = {
	__name = "product_variant_delete_batch";
	__index = product_variant_delete_batch;
}

local function cast_product_variant_delete_batch(t)
	return setmetatable(t, product_variant_delete_batch_mt)
end

local function new_product_variant_delete_batch(clear_cache, reindex, payload)
	return cast_product_variant_delete_batch({
		["clear_cache"] = clear_cache;
		["reindex"] = reindex;
		["payload"] = payload;
	})
end

return {
	cast = cast_product_variant_delete_batch;
	new = new_product_variant_delete_batch;
}
