--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_image_add class
local product_image_add = {}
local product_image_add_mt = {
	__name = "product_image_add";
	__index = product_image_add;
}

local function cast_product_image_add(t)
	return setmetatable(t, product_image_add_mt)
end

local function new_product_image_add(product_id, image_name, type, url, label, mime, position, content, product_variant_id, variant_ids, option_value_ids, store_id, lang_id, use_latest_api_version)
	return cast_product_image_add({
		["product_id"] = product_id;
		["image_name"] = image_name;
		["type"] = type;
		["url"] = url;
		["label"] = label;
		["mime"] = mime;
		["position"] = position;
		["content"] = content;
		["product_variant_id"] = product_variant_id;
		["variant_ids"] = variant_ids;
		["option_value_ids"] = option_value_ids;
		["store_id"] = store_id;
		["lang_id"] = lang_id;
		["use_latest_api_version"] = use_latest_api_version;
	})
end

return {
	cast = cast_product_image_add;
	new = new_product_image_add;
}
