--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_tax_add class
local product_tax_add = {}
local product_tax_add_mt = {
	__name = "product_tax_add";
	__index = product_tax_add;
}

local function cast_product_tax_add(t)
	return setmetatable(t, product_tax_add_mt)
end

local function new_product_tax_add(product_id, name, tax_rates, idempotency_key)
	return cast_product_tax_add({
		["product_id"] = product_id;
		["name"] = name;
		["tax_rates"] = tax_rates;
		["idempotency_key"] = idempotency_key;
	})
end

return {
	cast = cast_product_tax_add;
	new = new_product_tax_add;
}
