--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_option class
local product_option = {}
local product_option_mt = {
	__name = "product_option";
	__index = product_option;
}

local function cast_product_option(t)
	return setmetatable(t, product_option_mt)
end

local function new_product_option(id, product_option_id, name, description, sort_order, type, required, available, used_in_combination, option_items, additional_fields, custom_fields)
	return cast_product_option({
		["id"] = id;
		["product_option_id"] = product_option_id;
		["name"] = name;
		["description"] = description;
		["sort_order"] = sort_order;
		["type"] = type;
		["required"] = required;
		["available"] = available;
		["used_in_combination"] = used_in_combination;
		["option_items"] = option_items;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_product_option;
	new = new_product_option;
}
