--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_update_batch_payload_inner class
local product_update_batch_payload_inner = {}
local product_update_batch_payload_inner_mt = {
	__name = "product_update_batch_payload_inner";
	__index = product_update_batch_payload_inner;
}

local function cast_product_update_batch_payload_inner(t)
	return setmetatable(t, product_update_batch_payload_inner_mt)
end

local function new_product_update_batch_payload_inner(id, name, description, short_description, sku, model, price, special_price, sprice_create, sprice_expire, cost_price, old_price, fixed_cost_shipping_price, advanced_prices, quantity, increase_quantity, reduce_quantity, reserve_quantity, store_id, lang_id, status, type, condition, condition_description, visible, available_for_view, available_for_sale, avail_from, weight, length, width, height, dimensions_unit, weight_unit, manage_stock, in_stock, backorder_status, is_free_shipping, is_virtual, taxable, downloadable, warehouse_id, tax_class_id, categories_ids, meta_title, meta_description, meta_keywords, url, seo_url, manufacturer, manufacturer_id, mpn, gtin, upc, isbn, ean, barcode, images, related_products_ids, up_sell_products_ids, cross_sell_products_ids, tags, search_keywords, harmonized_system_code)
	return cast_product_update_batch_payload_inner({
		["id"] = id;
		["name"] = name;
		["description"] = description;
		["short_description"] = short_description;
		["sku"] = sku;
		["model"] = model;
		["price"] = price;
		["special_price"] = special_price;
		["sprice_create"] = sprice_create;
		["sprice_expire"] = sprice_expire;
		["cost_price"] = cost_price;
		["old_price"] = old_price;
		["fixed_cost_shipping_price"] = fixed_cost_shipping_price;
		["advanced_prices"] = advanced_prices;
		["quantity"] = quantity;
		["increase_quantity"] = increase_quantity;
		["reduce_quantity"] = reduce_quantity;
		["reserve_quantity"] = reserve_quantity;
		["store_id"] = store_id;
		["lang_id"] = lang_id;
		["status"] = status;
		["type"] = type;
		["condition"] = condition;
		["condition_description"] = condition_description;
		["visible"] = visible;
		["available_for_view"] = available_for_view;
		["available_for_sale"] = available_for_sale;
		["avail_from"] = avail_from;
		["weight"] = weight;
		["length"] = length;
		["width"] = width;
		["height"] = height;
		["dimensions_unit"] = dimensions_unit;
		["weight_unit"] = weight_unit;
		["manage_stock"] = manage_stock;
		["in_stock"] = in_stock;
		["backorder_status"] = backorder_status;
		["is_free_shipping"] = is_free_shipping;
		["is_virtual"] = is_virtual;
		["taxable"] = taxable;
		["downloadable"] = downloadable;
		["warehouse_id"] = warehouse_id;
		["tax_class_id"] = tax_class_id;
		["categories_ids"] = categories_ids;
		["meta_title"] = meta_title;
		["meta_description"] = meta_description;
		["meta_keywords"] = meta_keywords;
		["url"] = url;
		["seo_url"] = seo_url;
		["manufacturer"] = manufacturer;
		["manufacturer_id"] = manufacturer_id;
		["mpn"] = mpn;
		["gtin"] = gtin;
		["upc"] = upc;
		["isbn"] = isbn;
		["ean"] = ean;
		["barcode"] = barcode;
		["images"] = images;
		["related_products_ids"] = related_products_ids;
		["up_sell_products_ids"] = up_sell_products_ids;
		["cross_sell_products_ids"] = cross_sell_products_ids;
		["tags"] = tags;
		["search_keywords"] = search_keywords;
		["harmonized_system_code"] = harmonized_system_code;
	})
end

return {
	cast = cast_product_update_batch_payload_inner;
	new = new_product_update_batch_payload_inner;
}
