--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_add_batch_payload_inner class
local product_add_batch_payload_inner = {}
local product_add_batch_payload_inner_mt = {
	__name = "product_add_batch_payload_inner";
	__index = product_add_batch_payload_inner;
}

local function cast_product_add_batch_payload_inner(t)
	return setmetatable(t, product_add_batch_payload_inner_mt)
end

local function new_product_add_batch_payload_inner(name, description, short_description, sku, model, asin, upc, ean, gtin, mpn, isbn, barcode, price, old_price, cost_price, special_price, sprice_create, sprice_expire, avail_from, advanced_prices, fixed_cost_shipping_price, buyitnow_price, reserve_price, best_offer, quantity, manage_stock, product_type, marketplace_item_properties, specifics, is_free_shipping, taxable, status, condition, condition_description, visible, available_for_view, available_for_sale, is_virtual, in_stock, type, listing_type, listing_duration, downloadable, weight, length, width, height, weight_unit, dimensions_unit, store_id, lang_id, category_id, warehouse_id, categories_ids, related_products_ids, up_sell_products_ids, cross_sell_products_ids, stores_ids, tax_class_id, sales_tax, meta_title, meta_description, meta_keywords, search_keywords, harmonized_system_code, url, seo_url, external_product_link, manufacturer, manufacturer_id, backorder_status, images, tags, files)
	return cast_product_add_batch_payload_inner({
		["name"] = name;
		["description"] = description;
		["short_description"] = short_description;
		["sku"] = sku;
		["model"] = model;
		["asin"] = asin;
		["upc"] = upc;
		["ean"] = ean;
		["gtin"] = gtin;
		["mpn"] = mpn;
		["isbn"] = isbn;
		["barcode"] = barcode;
		["price"] = price;
		["old_price"] = old_price;
		["cost_price"] = cost_price;
		["special_price"] = special_price;
		["sprice_create"] = sprice_create;
		["sprice_expire"] = sprice_expire;
		["avail_from"] = avail_from;
		["advanced_prices"] = advanced_prices;
		["fixed_cost_shipping_price"] = fixed_cost_shipping_price;
		["buyitnow_price"] = buyitnow_price;
		["reserve_price"] = reserve_price;
		["best_offer"] = best_offer;
		["quantity"] = quantity;
		["manage_stock"] = manage_stock;
		["product_type"] = product_type;
		["marketplace_item_properties"] = marketplace_item_properties;
		["specifics"] = specifics;
		["is_free_shipping"] = is_free_shipping;
		["taxable"] = taxable;
		["status"] = status;
		["condition"] = condition;
		["condition_description"] = condition_description;
		["visible"] = visible;
		["available_for_view"] = available_for_view;
		["available_for_sale"] = available_for_sale;
		["is_virtual"] = is_virtual;
		["in_stock"] = in_stock;
		["type"] = type;
		["listing_type"] = listing_type;
		["listing_duration"] = listing_duration;
		["downloadable"] = downloadable;
		["weight"] = weight;
		["length"] = length;
		["width"] = width;
		["height"] = height;
		["weight_unit"] = weight_unit;
		["dimensions_unit"] = dimensions_unit;
		["store_id"] = store_id;
		["lang_id"] = lang_id;
		["category_id"] = category_id;
		["warehouse_id"] = warehouse_id;
		["categories_ids"] = categories_ids;
		["related_products_ids"] = related_products_ids;
		["up_sell_products_ids"] = up_sell_products_ids;
		["cross_sell_products_ids"] = cross_sell_products_ids;
		["stores_ids"] = stores_ids;
		["tax_class_id"] = tax_class_id;
		["sales_tax"] = sales_tax;
		["meta_title"] = meta_title;
		["meta_description"] = meta_description;
		["meta_keywords"] = meta_keywords;
		["search_keywords"] = search_keywords;
		["harmonized_system_code"] = harmonized_system_code;
		["url"] = url;
		["seo_url"] = seo_url;
		["external_product_link"] = external_product_link;
		["manufacturer"] = manufacturer;
		["manufacturer_id"] = manufacturer_id;
		["backorder_status"] = backorder_status;
		["images"] = images;
		["tags"] = tags;
		["files"] = files;
	})
end

return {
	cast = cast_product_add_batch_payload_inner;
	new = new_product_add_batch_payload_inner;
}
