--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- product_update class
local product_update = {}
local product_update_mt = {
	__name = "product_update";
	__index = product_update;
}

local function cast_product_update(t)
	return setmetatable(t, product_update_mt)
end

local function new_product_update(id, model, sku, name, description, short_description, price, old_price, special_price, sprice_create, sprice_expire, cost_price, fixed_cost_shipping_price, retail_price, tier_prices, reserve_price, buyitnow_price, taxable, tax_class_id, type, status, condition, visible, in_stock, avail, avail_from, product_class, brand_name, available_for_view, measure_unit, unit_price, stores_ids, store_id, lang_id, quantity, reserve_quantity, manage_stock, backorder_status, increase_quantity, reduce_quantity, low_stock_threshold, warehouse_id, weight, weight_unit, height, length, width, dimensions_unit, is_virtual, is_free_shipping, gtin, upc, mpn, ean, isbn, barcode, manufacturer, manufacturer_id, categories_ids, related_products_ids, up_sell_products_ids, cross_sell_products_ids, meta_title, meta_keywords, meta_description, seo_url, search_keywords, tags, delivery_code, package_details, country_of_origin, harmonized_system_code, shipping_template_id, processing_profile_id, when_made, is_supply, downloadable, materials, auto_renew, on_sale, production_partner_ids, manufacturer_info, report_request_id, disable_report_cache, reindex, clear_cache, check_process_status, specifics, shop_section_id, personalization_details, external_product_link, marketplace_item_properties, min_order_quantity, idempotency_key)
	return cast_product_update({
		["id"] = id;
		["model"] = model;
		["sku"] = sku;
		["name"] = name;
		["description"] = description;
		["short_description"] = short_description;
		["price"] = price;
		["old_price"] = old_price;
		["special_price"] = special_price;
		["sprice_create"] = sprice_create;
		["sprice_expire"] = sprice_expire;
		["cost_price"] = cost_price;
		["fixed_cost_shipping_price"] = fixed_cost_shipping_price;
		["retail_price"] = retail_price;
		["tier_prices"] = tier_prices;
		["reserve_price"] = reserve_price;
		["buyitnow_price"] = buyitnow_price;
		["taxable"] = taxable;
		["tax_class_id"] = tax_class_id;
		["type"] = type;
		["status"] = status;
		["condition"] = condition;
		["visible"] = visible;
		["in_stock"] = in_stock;
		["avail"] = avail;
		["avail_from"] = avail_from;
		["product_class"] = product_class;
		["brand_name"] = brand_name;
		["available_for_view"] = available_for_view;
		["measure_unit"] = measure_unit;
		["unit_price"] = unit_price;
		["stores_ids"] = stores_ids;
		["store_id"] = store_id;
		["lang_id"] = lang_id;
		["quantity"] = quantity;
		["reserve_quantity"] = reserve_quantity;
		["manage_stock"] = manage_stock;
		["backorder_status"] = backorder_status;
		["increase_quantity"] = increase_quantity;
		["reduce_quantity"] = reduce_quantity;
		["low_stock_threshold"] = low_stock_threshold;
		["warehouse_id"] = warehouse_id;
		["weight"] = weight;
		["weight_unit"] = weight_unit;
		["height"] = height;
		["length"] = length;
		["width"] = width;
		["dimensions_unit"] = dimensions_unit;
		["is_virtual"] = is_virtual;
		["is_free_shipping"] = is_free_shipping;
		["gtin"] = gtin;
		["upc"] = upc;
		["mpn"] = mpn;
		["ean"] = ean;
		["isbn"] = isbn;
		["barcode"] = barcode;
		["manufacturer"] = manufacturer;
		["manufacturer_id"] = manufacturer_id;
		["categories_ids"] = categories_ids;
		["related_products_ids"] = related_products_ids;
		["up_sell_products_ids"] = up_sell_products_ids;
		["cross_sell_products_ids"] = cross_sell_products_ids;
		["meta_title"] = meta_title;
		["meta_keywords"] = meta_keywords;
		["meta_description"] = meta_description;
		["seo_url"] = seo_url;
		["search_keywords"] = search_keywords;
		["tags"] = tags;
		["delivery_code"] = delivery_code;
		["package_details"] = package_details;
		["country_of_origin"] = country_of_origin;
		["harmonized_system_code"] = harmonized_system_code;
		["shipping_template_id"] = shipping_template_id;
		["processing_profile_id"] = processing_profile_id;
		["when_made"] = when_made;
		["is_supply"] = is_supply;
		["downloadable"] = downloadable;
		["materials"] = materials;
		["auto_renew"] = auto_renew;
		["on_sale"] = on_sale;
		["production_partner_ids"] = production_partner_ids;
		["manufacturer_info"] = manufacturer_info;
		["report_request_id"] = report_request_id;
		["disable_report_cache"] = disable_report_cache;
		["reindex"] = reindex;
		["clear_cache"] = clear_cache;
		["check_process_status"] = check_process_status;
		["specifics"] = specifics;
		["shop_section_id"] = shop_section_id;
		["personalization_details"] = personalization_details;
		["external_product_link"] = external_product_link;
		["marketplace_item_properties"] = marketplace_item_properties;
		["min_order_quantity"] = min_order_quantity;
		["idempotency_key"] = idempotency_key;
	})
end

return {
	cast = cast_product_update;
	new = new_product_update;
}
