--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- return_action_list_200_response class
local return_action_list_200_response = {}
local return_action_list_200_response_mt = {
	__name = "return_action_list_200_response";
	__index = return_action_list_200_response;
}

local function cast_return_action_list_200_response(t)
	return setmetatable(t, return_action_list_200_response_mt)
end

local function new_return_action_list_200_response(return_code, return_message, result)
	return cast_return_action_list_200_response({
		["return_code"] = return_code;
		["return_message"] = return_message;
		["result"] = result;
	})
end

return {
	cast = cast_return_action_list_200_response;
	new = new_return_action_list_200_response;
}
