--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- return_order_product class
local return_order_product = {}
local return_order_product_mt = {
	__name = "return_order_product";
	__index = return_order_product;
}

local function cast_return_order_product(t)
	return setmetatable(t, return_order_product_mt)
end

local function new_return_order_product(product_id, order_product_id, sku, name, quantity, reason, action, condition, customer_comment, additional_fields, custom_fields)
	return cast_return_order_product({
		["product_id"] = product_id;
		["order_product_id"] = order_product_id;
		["sku"] = sku;
		["name"] = name;
		["quantity"] = quantity;
		["reason"] = reason;
		["action"] = action;
		["condition"] = condition;
		["customer_comment"] = customer_comment;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_return_order_product;
	new = new_return_order_product;
}
