--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- return_status class
local return_status = {}
local return_status_mt = {
	__name = "return_status";
	__index = return_status;
}

local function cast_return_status(t)
	return setmetatable(t, return_status_mt)
end

local function new_return_status(id, name, additional_fields, custom_fields)
	return cast_return_status({
		["id"] = id;
		["name"] = name;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_return_status;
	new = new_return_status;
}
