--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- shipment_event class
local shipment_event = {}
local shipment_event_mt = {
	__name = "shipment_event";
	__index = shipment_event;
}

local function cast_shipment_event(t)
	return setmetatable(t, shipment_event_mt)
end

local function new_shipment_event(id, status, created_at, estimated_delivery_at, message, address, additional_fields, custom_fields)
	return cast_shipment_event({
		["id"] = id;
		["status"] = status;
		["created_at"] = created_at;
		["estimated_delivery_at"] = estimated_delivery_at;
		["message"] = message;
		["address"] = address;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_shipment_event;
	new = new_shipment_event;
}
