--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- shipment class
local shipment = {}
local shipment_mt = {
	__name = "shipment";
	__index = shipment;
}

local function cast_shipment(t)
	return setmetatable(t, shipment_mt)
end

local function new_shipment(id, order_id, name, warehouse_id, shipment_provider, tracking_numbers, created_at, modified_time, items, is_shipped, delivered_at, additional_fields, custom_fields)
	return cast_shipment({
		["id"] = id;
		["order_id"] = order_id;
		["name"] = name;
		["warehouse_id"] = warehouse_id;
		["shipment_provider"] = shipment_provider;
		["tracking_numbers"] = tracking_numbers;
		["created_at"] = created_at;
		["modified_time"] = modified_time;
		["items"] = items;
		["is_shipped"] = is_shipped;
		["delivered_at"] = delivered_at;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_shipment;
	new = new_shipment;
}
