--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- shipment_tracking_number class
local shipment_tracking_number = {}
local shipment_tracking_number_mt = {
	__name = "shipment_tracking_number";
	__index = shipment_tracking_number;
}

local function cast_shipment_tracking_number(t)
	return setmetatable(t, shipment_tracking_number_mt)
end

local function new_shipment_tracking_number(carrier_id, tracking_number, additional_fields, custom_fields)
	return cast_shipment_tracking_number({
		["carrier_id"] = carrier_id;
		["tracking_number"] = tracking_number;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_shipment_tracking_number;
	new = new_shipment_tracking_number;
}
