--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- special_price class
local special_price = {}
local special_price_mt = {
	__name = "special_price";
	__index = special_price;
}

local function cast_special_price(t)
	return setmetatable(t, special_price_mt)
end

local function new_special_price(value, avail, created_at, modified_at, expired_at, additional_fields, custom_fields)
	return cast_special_price({
		["value"] = value;
		["avail"] = avail;
		["created_at"] = created_at;
		["modified_at"] = modified_at;
		["expired_at"] = expired_at;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_special_price;
	new = new_special_price;
}
