--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- tax_class_states class
local tax_class_states = {}
local tax_class_states_mt = {
	__name = "tax_class_states";
	__index = tax_class_states;
}

local function cast_tax_class_states(t)
	return setmetatable(t, tax_class_states_mt)
end

local function new_tax_class_states(id, tax, tax_type, name, code, zip_codes, additional_fields, custom_fields)
	return cast_tax_class_states({
		["id"] = id;
		["tax"] = tax;
		["tax_type"] = tax_type;
		["name"] = name;
		["code"] = code;
		["zip_codes"] = zip_codes;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_tax_class_states;
	new = new_tax_class_states;
}
