--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- tax_class_zip_codes_range class
local tax_class_zip_codes_range = {}
local tax_class_zip_codes_range_mt = {
	__name = "tax_class_zip_codes_range";
	__index = tax_class_zip_codes_range;
}

local function cast_tax_class_zip_codes_range(t)
	return setmetatable(t, tax_class_zip_codes_range_mt)
end

local function new_tax_class_zip_codes_range(from, to, additional_fields, custom_fields)
	return cast_tax_class_zip_codes_range({
		["from"] = from;
		["to"] = to;
		["additional_fields"] = additional_fields;
		["custom_fields"] = custom_fields;
	})
end

return {
	cast = cast_tax_class_zip_codes_range;
	new = new_tax_class_zip_codes_range;
}
