--[[
  API2Cart OpenAPI

  API2Cart

  The version of the OpenAPI document: 1.1
  Contact: contact@api2cart.com
  Generated by: https://openapi-generator.tech
]]

-- webhook_create class
local webhook_create = {}
local webhook_create_mt = {
	__name = "webhook_create";
	__index = webhook_create;
}

local function cast_webhook_create(t)
	return setmetatable(t, webhook_create_mt)
end

local function new_webhook_create(entity, action, callback, label, fields, response_fields, active, lang_id, store_id, filtering_conditions, idempotency_key)
	return cast_webhook_create({
		["entity"] = entity;
		["action"] = action;
		["callback"] = callback;
		["label"] = label;
		["fields"] = fields;
		["response_fields"] = response_fields;
		["active"] = active;
		["lang_id"] = lang_id;
		["store_id"] = store_id;
		["filtering_conditions"] = filtering_conditions;
		["idempotency_key"] = idempotency_key;
	})
end

return {
	cast = cast_webhook_create;
	new = new_webhook_create;
}
